<?php

namespace App\Repository;

use App\Entity\Auteur;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAuteurByName($nom){
        // Recherche insensible à la casse ET aux accents avec SQL natif
        // Privilégie la version avec accents en triant par longueur du nom
        $conn = $this->getEntityManager()->getConnection();
        $normalizedName = strtoupper(str_replace(['é', 'è', 'ê', 'à', 'ô', 'û', 'ù', 'ï', 'î', 'ç'], ['e', 'e', 'e', 'a', 'o', 'u', 'u', 'i', 'i', 'c'], $nom));
        
        $sql = "SELECT id FROM auteur 
                WHERE UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(nom, 'é', 'e'), 'è', 'e'), 'ê', 'e'), 'à', 'a'), 'ô', 'o'), 'û', 'u'), 'ù', 'u'), 'ï', 'i'), 'î', 'i'), 'ç', 'c')) = :name
                ORDER BY LENGTH(nom) DESC
                LIMIT 1";
        
        $stmt = $conn->prepare($sql);
        $result = $stmt->executeQuery(['name' => $normalizedName])->fetchAssociative();
        
        return $result ? $this->find($result['id']) : null;
    }

    /**
     * Normalise un nom pour la comparaison (minuscules, sans accents, trié par mots)
     */
    public function normalizeForComparison(string $nom): array
    {
        $nom = trim(strtolower($nom));
        $nom = Auteur::removeAccents($nom);
        $parts = preg_split('/\s+/', $nom);
        sort($parts);
        return $parts;
    }

    /**
     * Recherche un auteur de manière intelligente en comparant les mots du nom
     * Gère les inversions type "Morrison Grant" vs "Grant Morrison"
     */
    public function findAuteurIntelligent(string $nomComplet): ?Auteur
    {
        $nomComplet = trim($nomComplet);
        
        // Recherche exacte d'abord
        $auteur = $this->getAuteurByName($nomComplet);
        if ($auteur) {
            return $auteur;
        }
        
        // Normaliser le nom recherché
        $normalizedSearch = $this->normalizeForComparison($nomComplet);

        // Récupérer les auteurs et comparer
        $auteurs = $this->createQueryBuilder('a')
            ->Where("1=1");

        foreach($normalizedSearch as $autSearch){
            $auteurs->andWhere('a.nom LIKE :nom')
            ->setParameter('nom', '%' . $autSearch . '%');
        }    
        $auteurs = $auteurs->getQuery()
            ->getResult();

        $countValide = 0;
        $LengthSearch = count($normalizedSearch);
        foreach ($auteurs as $auteur) {
            $normalizedAuteur = $this->normalizeForComparison($auteur->getNom());
            $cloneSearch = $normalizedSearch;
            foreach ($normalizedAuteur as $na) {
                if (in_array($na, $cloneSearch)) {
                    $countValide++;
                    $pos = array_search($na, $cloneSearch);
                    unset($cloneSearch[$pos]);
                }
                else{
                    $countValide = 0;
                    break;
                }
            }
            if($countValide == $LengthSearch){
                return $auteur;
            }
        }
        
        return null;
    }

    /**
     * Récupère tous les auteurs triés par nom
     */
    public function findAllOrderedByNom(): array
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.nom', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Récupère les auteurs groupés par initiale (sans accent)
     */
    public function findAllGroupedByInitiale(): array
    {
        $auteurs = $this->findAllOrderedByNom();
        $grouped = [];
        
        foreach ($auteurs as $auteur) {
            $initiale = $auteur->getInitiale();
            if (!isset($grouped[$initiale])) {
                $grouped[$initiale] = [];
            }
            $grouped[$initiale][] = $auteur;
        }
        
        ksort($grouped);
        return $grouped;
    }

    /**
     * Récupère toutes les initiales disponibles (sans accent)
     */
    public function findAllInitiales(): array
    {
        $auteurs = $this->findAll();
        $initiales = [];
        
        foreach ($auteurs as $auteur) {
            $initiale = $auteur->getInitiale();
            if (!in_array($initiale, $initiales)) {
                $initiales[] = $initiale;
            }
        }
        
        sort($initiales);
        return $initiales;
    }

    /**
     * Recherche les auteurs par terme de recherche
     */
    public function searchAuteurs(string $term): array
    {
        return $this->createQueryBuilder('a')
            ->where('UPPER(a.nom) LIKE :term')
            ->setParameter(':term', '%' . strtoupper($term) . '%')
            ->orderBy('a.nom', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
