<?php

namespace App\Repository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAuteurByName($nom){
        return $this->createQueryBuilder('a')
            ->where('UPPER(a.nom) = :name')
            ->setParameter(':name', strtoupper($nom))
            ->getQuery()->getOneOrNullResult();
    }
}
