<?php

namespace App\Repository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCollectionByName($name){
        return $this->createQueryBuilder('c')
            ->where('UPPER(c.nom) = :name')
            ->setParameter(':name', strtoupper($name))
            ->getQuery()->getOneOrNullResult();
    }
}
