<?php

namespace App\Repository;

/**
 * EditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEditionByName($name){
        return $this->createQueryBuilder('e')
            ->where('UPPER(e.nom) = :name')
            ->setParameter(':name', strtoupper($name))
            ->distinct('e.name')
            ->getQuery()->getOneOrNullResult();
    }
}
