<?php

namespace App\Repository;

/**
 * LienAuteurLivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienAuteurLivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLienByAuteurAndLivre($auteur, $livre){
        return $this->createQueryBuilder('lal')
            ->where('lal.auteur = :auteur')
            ->andWhere('lal.livre = :livre')
            ->setParameter(':auteur', $auteur)
            ->setParameter(':livre', $livre)
            ->getQuery()->getResult();
    }

    public function getListeAuteur($livre){
        return $this->createQueryBuilder('lal')
            ->Where('lal.livre = :livre')
            ->setParameter(':livre', $livre)
            ->getQuery()->getResult();
    }

    public function getCountLien($auteur){
        $qb = $this->createQueryBuilder('lal');
        return $qb->select('count(lal.id)')
            ->Where('lal.auteur = :auteur')
            ->setParameter(':auteur', $auteur)
            ->getQuery()->getSingleScalarResult();
    }


}
