<?php

namespace App\Repository;

/**
 * LienUserLivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienUserLivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLivreByUser($user){
        return $this->createQueryBuilder('lul')
            ->innerJoin('lul.livre', 'l')
            ->where('lul.user = :user')
            ->setParameter(':user', $user)
            ->orderBy('l.titre', 'ASC')
            ->getQuery()->getResult();
    }
}
