<?php

namespace App\Repository;

/**
 * LienAuteurLivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienAuteurLivreRepository extends \Doctrine\ORM\EntityRepository
{
}
